django project/Exc2/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^myapp/', include('myapp.urls', namespace = 'myapp')),
]

django project/myapp/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index_default'),
    url(r'^index/', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    #url(r'^detail/(?P<course_title>[a-zA-Z ]+)/', views.detail, name='detail'),
    url(r'^detail/(?P<course_num>[0-9]+)/', views.detail, name='detail'),
    url(r'^topics/$',views.topics, name='topics'),
    url(r'^addtopic/$', views.addtopic, name='addtopic'),
    url(r'^topics/(?P<topic_id>\d+)/',views.topicdetail, name='topicdetail'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$',views.user_logout, name='logout'),
    url(r'^mycourses/$', views.mycourses, name='mycourses'),
    url(r'^forgotpass/$',views.forgotpass, name='forgotpass')
    ]

django project/myapp/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Author(models.Model):
    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    birthdate = models.DateField()
    #3c - Comment the 'age' field in Author
    #age = models.IntegerField()
    #3b
    city = models.CharField(max_length=100, blank=True, null=True)
    newField = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        if (self.city != None or self.city == ''):
            return str(self.firstName + ' ' + self.lastName + ' born ' + str(self.birthdate) + ' lives in ' + self.city)
        else:
            return str(self.firstName + ' ' + self.lastName + ' born ' + str(self.birthdate))

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey(Author)
    in_stock = models.BooleanField(default=True)
    #3a
    numpages = models.IntegerField(null=True, validators= [MinValueValidator(50),MaxValueValidator(1000)])
    def __str__(self):
        if (self.in_stock == True):
            return str(self.title + ' by ' + self.author.firstName + ' ' + self.author.lastName + ' ' + str(self.numpages) + ' pages')
        else:
            return str(self.title + ' by ' + self.author.firstName + ' ' + self.author.lastName + ' ' + str(self.numpages) + ' pages ' + 'NOT-IN-STOCK')

class Student(User):
    PROVINCE_CHOICES = (
        ('AB','Alberta'), # First value is stored in db, the second is descriptive
        ('MB', 'Manitoba'),
        ('ON', 'Ontario'),
        ('QC', 'Quebec'),
    )
    address = models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province=models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    age = models.IntegerField()
    profile_pic = models.ImageField(upload_to='myapp/images', blank=True, null=True)
    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Course(models.Model):
    course_no = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=200)
    textbook = models.ForeignKey(Book)
    students = models.ManyToManyField(Student, null=True, blank=True)
    def __str__(self):
        return str(str(self.course_no) + " '" + self.title + "' " + " uses " + str(self.textbook.title))

class Topic(models.Model):
    subject = models.CharField(max_length=100, unique=True)
    intro_course = models.BooleanField(default=True)
    NO_PREFERENCE = 0
    MORNING = 1
    AFTERNOON = 2
    EVENING = 3
    TIME_CHOICES = (
        (0, 'No preference'),
        (1, 'Morning'),
        (2, 'Afternoon'),
        (3, 'Evening')
    )
    time = models.IntegerField(default=0, choices=TIME_CHOICES)
    num_responses = models.IntegerField(default=0)
    avg_age =models.IntegerField(default=20)
    def __str__(self):
        return self.subject

django project/myapp/forms.py
from django import forms
from myapp.models import Topic, Student

class TopicForm(forms.ModelForm):
    subject = forms.CharField(label='Subject',max_length=100, required=False)
    intro_course = forms.BooleanField(label='This should be an introductory level course', required=False)
    avg_age = forms.IntegerField(label='What is Your Age')
    class Meta:
        model=Topic
        fields='__all__'
        widgets={
            'time':forms.RadioSelect(attrs={'class':'radio'}),

        }

class InterestForm(forms.Form):
    CHOICES=(
        (0,'no'),
        (1,'yes')
    )
    interested= forms.CharField(widget=forms.RadioSelect(choices=CHOICES))
    age = forms.IntegerField(initial=20, label='Age of Use')
    comments = forms.Textarea(attrs={'required':'false'})
    comments.id_for_label('Additional Conditions')

class RegistrationForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('first_name', 'last_name', 'username','email','password','address','city','age','profile_pic')

django project/myapp/views.py
from django.shortcuts import render

# Create your views here.

# Import necessary classes
from django.http import HttpResponse,HttpResponseRedirect
from django.core.urlresolvers import reverse
from myapp.models import Author, Book, Course,Topic, Student
from django.shortcuts import get_object_or_404, render
from myapp.forms import TopicForm, InterestForm, RegistrationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.core.mail import send_mail
from django.views import View


# Create your views here.
# def index(request):
#     #Courses
#     courselist = Course.objects.all()[:10]
#     response = HttpResponse()
#     heading1 = '<p>' + 'List of courses: ' + '</p>'
#     response.write(heading1)
#     for course in courselist:
#         para = '<p>' + str(course) + '</p>'
#         response.write(para)
#
#     #Authors
#     authorlist = Author.objects.filter().order_by('-birthdate')[:5]
#     #response = HttpResponse()
#     heading1 = '<p>' + 'List of Authors: ' + '</p>'
#     response.write(heading1)
#     response.write(str(type(authorlist)))
#     for author in authorlist:
#         para = '<p>' + str(author) + '</p>'
#         response.write(para)
#
#     return response
#
# def about(request):
#     response = HttpResponse()
#     heading = 'This is a Course Listing APP.'
#     response.write(heading)
#     return response
#
# def detail(request, course_title):
#     response = HttpResponse()
#     heading = '<strong>Course details: <br/><br/></strong>'
#     response.write(heading)
#     #Print the course details
#     #course_list = Course.objects.filter(course_no=course_num)[0]
#     course_list = get_object_or_404(Course, title=course_title)
#     response.write('Course Number: ' + str(course_list.course_no) + '<br/>Course Title: ' + str(course_list.title)
#                    + '<br/>Book Title: ' + str(course_list.textbook.title))
#     return response
def index(View):
    courselist = Course.objects.all().order_by('title')[:10]

    if 'visit' in View.COOKIES:
        visit = View.COOKIES['visit']
        visit = int(visit)
        visit += 1
        visit = str(visit)
        response = render(View, 'myapp/index.html', {'courselist': courselist })
        response.set_cookie('counter', str(visit));
        return response
    else:
        response = render(View, 'myapp/index.html', {'courselist': courselist})
        visit = visit = str(1)
        response.set_cookie('visit', visit);
        return response

def about(request):
    return render(request,'myapp/about.html')


def detail(View,course_num):
    courselist=get_object_or_404(Course,course_no=course_num)
    return render(View,'myapp/detail.html', { 'courselist': courselist })

def topics(request):
    topiclist = Topic.objects.all()[:10]
    return render(request, 'myapp/topic.html',
{'topiclist':   topiclist})

def addtopic(request):
    topiclist = Topic.objects.all()
    if request.method=='POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.num_responses=1
            topic.save()
            return HttpResponseRedirect(reverse('myapp:topics'))
    else:
        form=TopicForm()
    return render(request, 'myapp/addtopic.html', {'form':form,
'topiclist':topiclist})

def topicdetail(request, topic_id):
    topicdetails = Topic.objects.get(id = topic_id)
    if(request.method=='POST'):
        form = InterestForm(request.POST)
        if(form.is_valid()):
            if(request.POST['interested'] == '1'):
                topicdetails.num_responses += 1;
                avg_age = (topicdetails.avg_age + int(request.POST['age']))/2
                topicdetails.avg_age = avg_age
                topicdetails.save()
        return render(request, 'myapp/topicdetail.html', {'topicdetails': topicdetails, 'form':form})
    else:
        form = InterestForm()
        return render(request, 'myapp/topicdetail.html', {'topicdetails': topicdetails, 'form':form})
def register(request):
        if(request.method == 'POST'):
            form = RegistrationForm(request.POST,request.FILES)
            if(form.is_valid()):
                student=form.save(commit=False)
                student.save()
                student.set_password(student.password)
                student.save()
                return HttpResponseRedirect(reverse('myapp:register'))

        else:
            form=RegistrationForm()
            return render(request,'myapp/Register.html',{'form': form})


def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('myapp:index'))  #
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')

@login_required()
def user_logout(request):
    #global user
    logout(request)
    return render(request, 'myapp/logout.html')

def mycourses(request):
    mycourselist = Course.objects.filter(students__first_name__contains=request.user)
    return render(request,'myapp/mycourses.html',{'mycourselist': mycourselist})
#def mycourses(request):

def forgotpass(request):
    email = request.POST['email']
    passwords = Student.objects.get(email= email)

    send_mail('Hey how are you ? Dont worry here is your password','Hey how are you ? Dont worry here is your password{0}'.format(passwords.password),'madhuwindsor@gmail.com',email, fail_silently=False)
    return render(request, 'myapp/forgotpass.html')

django project/myapp/templates/myapp/Register.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<h2>Welcome To Registration Page</h2>
  <form method="POST" action="" enctype="multipart/form-data" style="max-width: 800px; margin:auto">
    {% csrf_token %}
    <h2>Please Sign Up <small>It's free and always will be.</small></h2>
			<hr class="colorgraph">
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
                        <input type="text" name="first_name" id="first_name" class="form-control input-lg" placeholder="First Name" tabindex="1">
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<input type="text" name="last_name" id="last_name" class="form-control input-lg" placeholder="Last Name" tabindex="2">
					</div>
				</div>
			</div>
			<div class="form-group">
				<input type="text" name="username" id="display_name" class="form-control input-lg" placeholder="User Name" tabindex="3">
			</div>
			<div class="form-group">
				<input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email Address" tabindex="4">
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password" tabindex="5">
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<input type="text" name="address" id="address" class="form-control input-lg" placeholder="Address" tabindex="6">
					</div>
				</div>
			</div>
            <div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<input type="text" name="city" id="city" class="form-control input-lg" placeholder="City" tabindex="5">
					</div>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<div class="form-group">
						<input type="text" name="age" id="age" class="form-control input-lg" placeholder="Age" tabindex="6">
					</div>
				</div>
			</div>
      <div class="form-group">
				<input type="file" name="profile_pic" id="profile_pic" class="form-control input-lg" placeholder="Please upload your Profile picture" tabindex="3">
			</div>
			<div class="row">
				<div class="col-xs-4 col-sm-3 col-md-3">
					<span class="button-checkbox">
						<button type="button" class="btn" data-color="info" tabindex="7">I Agree</button>
                        <input type="checkbox" name="t_and_c" id="t_and_c" class="hidden" value="1">
					</span>
				</div>
				<div class="col-xs-8 col-sm-9 col-md-9">
					 By clicking <strong class="label label-primary">Register</strong>, you agree to the <a href="#" data-toggle="modal" data-target="#t_and_c_m">Terms and Conditions</a> set out by this site, including our Cookie Use.
				</div>
			</div>

			<hr class="colorgraph">
			<div class="row">
				<button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Register" type="Submit">Register</button>
			</div>
  </form>

django project/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block body_block %}

<h1> This is a course listing app</h1>
{% endblock %}

django project/myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Page</title>
</head>
<body>
<h1> This is a course listing app</h1>

<p><a href="/myapp/">Index page</a></p>
<p><a href="{% url 'myapp:index' %}">Back to Index</a></p>
</body>
</html>

django project/myapp/templates/myapp/addtopic.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h2>You can add a new Topic here</h2>
    <h3>Available Topics </h3>
    {% if topiclist %}
        <ul>
        {% for topic in topiclist %}
            <li>
            {{ topic.subject }}
            <ul>
                <li>
                    IntroToCourse: {{ topic.intro_course }}
                </li>
            </ul>
            </li>
        {% endfor %}
        </ul>
    {% endif %}
<hr />
    <h2>Or Propose a New Topic?</h2>
     <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_ul }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>


{% endblock %}

django project/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<title>Course Listing APP - {% block title %}Welcome!{% endblock %}</title>
</head>

<body>
<div>
<h1>{% block myhdg %}Hello {{user.first_name}} {% endblock %}</h1>
            {% block body_block %}*** {% endblock %}
</div>
<hr />
<div>
<ul class="nav nav-tabs nav-justified">
<li class="hbar1"><a href="/myapp/about/">Find out about this site</a></li>
<li class="hbar1"><a href = "{% url 'myapp:index' %}">Main Page</a><br/></li>
<li class="hbar1"><a href = "{% url 'myapp:topics' %}">Topics</a><br/></li>
    {% if user.first_name %}
        <li class="hbar1"><a href ="{% url 'myapp:logout' %}">Log out </a></li>
        <li class="hbar1"><a href ="{% url 'myapp:mycourses' %}">My Courses </a></li>
        {% else %}
        <li class="hbar1"><a href ="{% url 'myapp:login' %}">Login</a></li>

        <li class="hbar1"><a href="{% url 'myapp:register' %}">Register</a> </li>
    {% endif %}

</ul>
</div>
</body>
</html>

django project/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}

           <h2> Course Details</h2>
           <ol>
               <ul>Course no : {{courselist.course_no }}</ul>
               <ul>Course Title : {{courselist.title}}</ul>
               <ul>Text Book : {{courselist.textbook}}</ul>
           </ol>


{% endblock %}

django project/myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details Page</title>
</head>
<body>

           <h2> Course Details</h2>
           <ol>
               <ul>Course no : {{courselist.course_no }}</ul>
               <ul>Course Title : {{courselist.title}}</ul>
               <ul>Text Book : {{courselist.textbook}}</ul>
           </ol>

<p><a href="{% url 'myapp:index' %}">Back to Index</a></p>
</body>
</html>

django project/myapp/templates/myapp/forgotpass.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body style="width: 500px; margin: 0 auto;">
    <h2>Forgot Password</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        <!--<div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" id="username" placeholder="Email">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" id="password" placeholder="Password">
        </div>-->

        <h3 class="form-signin-heading">Welcome Back! Please Sign In</h3>
			  <hr class="colorgraph"><br>

			  <input type="text" class="form-control" name="username" placeholder="Username" required="" autofocus="" />
			  <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="Submit">Login</button>
    </form>
</body>
</html>

django project/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if courselist %}
<h2>List of Courses</h2>
<ol>
            {% for course  in courselist %}
                <li class="list-group-item list-group-item-info" style="text-align: center; float: inherit"><a href="/myapp/detail/{{course.course_no}}/">{{ course.title}}</a> </li>
            {% endfor %}
</ol>

    {% else %}
<strong>There are no available courses!</strong>
    {% endif %}

{% endblock %}

django project/myapp/templates/myapp/index0.html
<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<title>Course Listing APP</title>
</head>
<body>
    {% if courselist %}
<h2>List of Courses</h2>
<ol>
            {% for course  in courselist %}
<li class="">{{ course.title}} </li>
            {% endfor %}
</ol>

    {% else %}
<strong>There are no available courses!</strong>
    {% endif %}

<p><a href="/myapp/about">About page</a></p>
<p><a href="{% url 'myapp:about' %}">About Page Using Namespace</a></p>
</body>
</html>

django project/myapp/templates/myapp/login.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
</head>
<body style="width: 500px; margin: 0 auto;">
    <h2>Login</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        <!--<div class="form-group">
            <label>Username</label>
            <input type="text" class="form-control" id="username" placeholder="Email">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" id="password" placeholder="Password">
        </div>-->

        <h3 class="form-signin-heading">Welcome Back! Please Sign In</h3>
			  <hr class="colorgraph"><br>

			  <input type="text" class="form-control" name="username" placeholder="Username" required="" autofocus="" />
			  <input type="password" class="form-control" name="password" placeholder="Password" required=""/>

			  <button class="btn btn-lg btn-primary btn-block"  name="Submit" value="Login" type="Submit">Login</button>
              <li class="hbar1"> <a href="forgotpass.html"> Forgot Passsword</a> </li>
    </form>
</body>
</html>

django project/myapp/templates/myapp/logout.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
</head>
<body style="width: 500px; text-align:center;">
    <h2>User has been logged out!</h2>
    <h4>Click <a href="{% url "myapp:index" %}">Here</a> to go to the Home page</h4>
</body>
</html>

django project/myapp/templates/myapp/mycourses.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if user.student %}
        {% if mycourselist %}
            <h2> List of Courses</h2>
            <ul>
            {% for course in mycourselist %}
                <li>
                {{ course.title }}
                </li>
            {% endfor %}
            <br/>
            </ul>
            {% else %}
            <strong> You are not registered. Please register for courses </strong>
            {% endif %}
        {% else %}
        <h1> Not a Student</h1>
    {% endif %}
{% endblock %}

django project/myapp/templates/myapp/topic.html
{% extends 'myapp/base.html' %}

{% block body_block %}
 {% if topiclist %}
        <h2>List of Topics</h2>
        <ul>

               {% for topic in topiclist %}

                   <li> <a class="linkref" href="{% url 'myapp:topicdetail' topic.id %}">{{topic.subject}}</a>
                   </li>

               {% endfor %}
        <br />
            <a href="{% url 'myapp:addtopic' %}">Add a new Topic</a>

        </ul>

    {% else %}
        <strong>There are no available Topics!</strong>
    {% endif %}

{% endblock %}